services:
  db:
    image: redis:latest
    ports:
      - 0.0.0.0:6379:6379
  postgres:
    image: postgres:latest
    ports:
      - 0.0.0.0:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
