services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://db:6379
      - TOKEN=${TOKEN}
  db:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
