services:
  app:
    build:
      context: ../discord
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://db:6379
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - BASE_URL=${BASE_URL}
  db:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
